name: Continuous Deployment

env:
  build-artifact-name: zippy-app
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group `push` events
  # - Is pull request? Group `pull_request` events
  group:
    ${{ github.workflow }}-${{ github.event_name == 'push' && github.base_ref ||
    github.head_ref }}
  # Run merge runs in sequence. Cancel in progress pull request runs.
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Lint all projects
        run: yarn lint

  test:
    name: Unit and integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run all unit and integration tests
        run: yarn test

  build:
    name: Build web app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - name: Install package dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Get GitHub repository name
        id: repository-name
        run: echo "::set-output name=name::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
      - name: Build web app
        run: yarn build --base-href=/${{ steps.repository-name.outputs.name }}/
      - name: Add 404 page with GitHub Pages support
        run: cp build/github-pages/404.html ./dist/${{ env.build-artifact-name }}
      - name: Upload web app build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.build-artifact-name }}
          path: ./dist/${{ env.build-artifact-name }}
          if-no-files-found: error

  deploy:
    name: Deploy web app to GitHub Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build
      - lint
      - test
    runs-on: ubuntu-latest

    env:
      build-artifact-path: ./zippy-app

    steps:
      # Necessary for JamesIves/github-pages-deploy-action
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.build-artifact-name }}
          path: ${{ env.build-artifact-path }}

      - name: Deploy app to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: ${{ env.build-artifact-path }}
